[package]
name = "dendron-nvim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
home = "0.5.4"
juniper = "0.15.10"
neovim-lib = "0.6.1"
serde = "1.0.150"
serde_yaml = "0.9.14"
sqlite = "0.30.3"
